# Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES
#
# SPDX-License-Identifier: BSD-3-Clause

# Note: Project metadata (name, version, dependencies, classifiers) is
# declared in pyproject.toml, which is generated from pyproject.toml.template
# by configure.sh.  This file only contains build mechanics (CMake extension
# compilation, wheel packaging, and package layout).

import os
import sys
import json
import shutil
import pathlib
import subprocess
import sysconfig

from setuptools import setup, Extension
from setuptools.command.build_ext import build_ext
from setuptools.command.editable_wheel import editable_wheel
from wheel.bdist_wheel import bdist_wheel


# ---------------------------------------------------------------------------
# Guard: verify that configure.sh has been run before building.
# ---------------------------------------------------------------------------
_pyproject = os.path.join(os.path.dirname(os.path.abspath(__file__)), "pyproject.toml")
if os.path.exists(_pyproject):
    with open(_pyproject) as _f:
        if "[project]" not in _f.read():
            raise RuntimeError(
                "pyproject.toml does not contain [project] metadata.\n"
                "Run configure.sh first:\n"
                "  CUDA_PATH=/usr/local/cuda bash configure.sh"
            )
else:
    raise RuntimeError(
        "pyproject.toml not found.\n"
        "Run configure.sh first:\n"
        "  CUDA_PATH=/usr/local/cuda bash configure.sh"
    )



# ---------------------------------------------------------------------------
# Capture the build-time jax version so cuquantum.{densitymat,stabilizer}.jax
# can warn at import time whenever the runtime jax version differs from the
# build-time jax version. JAX is effort-versioned (see
# https://docs.jax.dev/en/latest/jep/9419-jax-versioning.html), so any
# difference -- including patch bumps -- may shift the FFI capsule layout
# that the C++ FFI capsules were compiled against. The observed failure
# under such mismatch is "No FFI handler registered for operator_action
# on platform CUDA" at the first primitive call.
# ---------------------------------------------------------------------------
def _write_jax_build_info() -> None:
    """Write _build_info.py (JAX_BUILD_VERSION, PROJECT_NAME, check_jax_abi)
    into each jax extension subpackage so the runtime can warn on jax-version
    mismatch with what the C++ FFI capsules were compiled against."""
    try:
        import jax  # build env import
        version = jax.__version__
    except Exception:
        version = ""
    here = os.path.dirname(os.path.abspath(__file__))
    # Pull the distribution name from pyproject.toml (generated by configure.sh).
    project_name = ""
    try:
        import re as _re
        with open(os.path.join(here, "pyproject.toml")) as _f:
            m = _re.search(r'^name\s*=\s*"([^"]+)"', _f.read(), _re.MULTILINE)
            if m:
                project_name = m.group(1)
    except Exception:
        pass
    src = (
        '# Auto-generated by setup.py at build time; do not edit.\n'
        f'JAX_BUILD_VERSION = "{version}"\n'
        f'PROJECT_NAME = "{project_name}"\n'
        '\n'
        'def check_jax_abi() -> None:\n'
        '    """Warn whenever the runtime jax version differs from the\n'
        '    build-time jax version. JAX uses effort-based versioning, so\n'
        '    any difference -- patch bumps included -- may shift the FFI\n'
        '    capsule layout these bindings were compiled against."""\n'
        '    if not JAX_BUILD_VERSION:\n'
        '        return\n'
        '    import jax, warnings\n'
        '    if jax.__version__ != JAX_BUILD_VERSION:\n'
        '        warnings.warn(\n'
        '            f"JAX version mismatch: {PROJECT_NAME} was built using "\n'
        '            f"JAX {JAX_BUILD_VERSION}, current runtime is JAX "\n'
        '            f"{jax.__version__}. Rebuild against the runtime jax if "\n'
        '            f"you see issues.",\n'
        '            RuntimeWarning, stacklevel=3)\n'
    )
    for pkg in ("cuquantum/densitymat/jax", "cuquantum/stabilizer/jax"):
        with open(os.path.join(here, pkg, "_build_info.py"), "w") as f:
            f.write(src)

_write_jax_build_info()


def _wheel_tag():
    vi     = sys.version_info
    python = f"cp{vi.major}{vi.minor}"
    abi    = python + ("d" if sysconfig.get_config_var("Py_DEBUG") else "")
    plat   = sysconfig.get_platform().replace("-", "_").replace(".", "_")
    return f"{python}-{abi}-{plat}"


class CMakeExtension(Extension):
    def __init__(self, name: str, source_dir: str = ""):
        super().__init__(name, sources=[])
        self.source_dir = os.path.abspath(source_dir)

class CMakeBuild(build_ext):
    def run(self):
        try:
            out = subprocess.check_output(["cmake", "--version"])
        except OSError:
            raise RuntimeError(
                "CMake must be installed to build the following extensions: "
                + ", ".join(e.name for e in self.extensions)
            )

        for ext in self.extensions:
            self.build_extension(ext)

    def build_extension(self, ext):
        extdir = os.path.abspath(os.path.dirname(self.get_ext_fullpath(ext.name)))
        cmake_args = []

        additional_cmake_args = os.environ.get("CMAKE_ARGS", "")
        if additional_cmake_args:
            cmake_args += additional_cmake_args.split()

        cfg = "Debug" if self.debug else "Release"
        build_args = ["--config", cfg]

        cmake_args += ["-DCMAKE_BUILD_TYPE=" + cfg]
        cmake_args += [f"-DPython3_EXECUTABLE={sys.executable}"]
        build_args += ["--", "-j2"]

        env = os.environ.copy()
        env["CXXFLAGS"] = '{} -DVERSION_INFO=\\"{}\\"'.format(
            env.get("CXXFLAGS", ""), self.distribution.get_version()
        )
        # Per-extension build subdir so multiple CMakeExtension targets do not
        # share a CMakeCache.
        ext_build_temp = os.path.join(self.build_temp, ext.name)
        if not os.path.exists(ext_build_temp):
            os.makedirs(ext_build_temp)
        subprocess.check_call(
            ["cmake", ext.source_dir] + cmake_args, cwd=ext_build_temp, env=env
        )
        subprocess.check_call(
            ["cmake", "--build", ".", "--verbose"] + build_args, cwd=ext_build_temp
        )
        dso_dir = os.path.join(extdir, "cuquantum/lib")
        os.makedirs(dso_dir, exist_ok=True)
        for dso in pathlib.Path(ext_build_temp).rglob("*.so"):
            shutil.copy2(dso, dso_dir)

class CustomBuildEditable(editable_wheel):
    """
    Write a minimal editable wheel whose finder maps only cuquantum.densitymat.jax and cuquantum.lib —
    no NAMESPACES, so cuquantum and cuquantum.densitymat are left to the regular import machinery.
    """
    def run(self):
        # Build C++ extension in-place
        self.reinitialize_command("build_ext", inplace=1)
        self.run_command("build_ext")
        # Write our custom editable wheel — do NOT call super().run() as that
        # generates a NAMESPACES-based finder that clobbers cuquantum.__path__.
        self._write_editable_wheel()

    def _write_editable_wheel(self):
        import hashlib, base64, zipfile

        project_dir = os.path.dirname(os.path.abspath(__file__))
        dist        = self.distribution
        raw_name    = dist.get_name()
        version     = dist.get_version()
        safe_name   = raw_name.replace("-", "_").replace(".", "_")
        dist_info   = f"{safe_name}-{version}.dist-info"
        finder_mod  = f"__editable_{safe_name}_finder__"
        pth_file    = f"__editable_{safe_name}.pth"

        finder_src = f"""\
# Auto-generated by setup.py — do not edit.
import sys
from pathlib import Path
from importlib.machinery import ModuleSpec, PathFinder
from importlib.util import spec_from_file_location

MAPPING = {{
    "cuquantum.densitymat.jax": {os.path.join(project_dir, "cuquantum", "densitymat", "jax")!r},
    "cuquantum.stabilizer.jax": {os.path.join(project_dir, "cuquantum", "stabilizer", "jax")!r},
    "cuquantum.lib": {os.path.join(project_dir, "cuquantum", "lib")!r},
}}

class _Finder:
    @classmethod
    def find_spec(cls, fullname, path=None, target=None):
        if fullname in MAPPING:
            pkg_dir = Path(MAPPING[fullname])
            init = pkg_dir / "__init__.py"
            if init.exists():
                # Regular package: point directly at __init__.py.
                # This branch is for cuquantum.densitymat.jax, which is a regular package.
                return spec_from_file_location(
                    fullname, str(init),
                    submodule_search_locations=[str(pkg_dir)],
                )
            elif pkg_dir.is_dir():
                # Namespace package: no __init__.py needed; sub-imports still work.
                # This branch is for cuquantum.lib, which is a namespace package.
                spec = ModuleSpec(fullname, None, is_package=True)
                spec.submodule_search_locations = [str(pkg_dir)]
                return spec
            return None
        parent, _, _ = fullname.rpartition(".")
        if parent in MAPPING:
            # For children, pass the parent dir so FileFinder finds the child.
            return PathFinder.find_spec(fullname, path=[MAPPING[parent]])
        return None

def install():
    if _Finder not in sys.meta_path:
        sys.meta_path.insert(0, _Finder)
"""

        pth_src    = f"import {finder_mod}; {finder_mod}.install()\n"
        metadata   = f"Metadata-Version: 2.1\nName: {raw_name}\nVersion: {version}\n"
        tag        = _wheel_tag()
        wheel_hdr  = (f"Wheel-Version: 1.0\nGenerator: setuptools\n"
                      f"Root-Is-Purelib: false\nTag: {tag}\n")
        direct_url = json.dumps({"url": f"file://{project_dir}",
                                 "dir_info": {"editable": True}})

        def _record(data: bytes) -> str:
            h = base64.urlsafe_b64encode(
                    hashlib.sha256(data).digest()).rstrip(b"=").decode()
            return f"sha256={h},{len(data)}"

        entries = {
            f"{finder_mod}.py":             finder_src.encode(),
            pth_file:                       pth_src.encode(),
            f"{dist_info}/METADATA":        metadata.encode(),
            f"{dist_info}/WHEEL":           wheel_hdr.encode(),
            f"{dist_info}/direct_url.json": direct_url.encode(),
        }
        record = "\n".join(f"{k},{_record(v)}" for k, v in entries.items())
        record += f"\n{dist_info}/RECORD,,\n"
        entries[f"{dist_info}/RECORD"] = record.encode()

        os.makedirs(self.dist_dir, exist_ok=True)
        whl = os.path.join(self.dist_dir,
                           f"{safe_name}-{version}-{tag}.whl")
        with zipfile.ZipFile(whl, "w", zipfile.ZIP_DEFLATED) as zf:
            for fname, data in entries.items():
                zf.writestr(fname, data)
        print(f"editable wheel written to {whl}")


class CustomBdistWheel(bdist_wheel):
    def finalize_options(self):
        super().finalize_options()
        self.root_is_pure = False

setup(
    ext_modules=[
        CMakeExtension("cudensitymat_jax_cppsrc",
                       source_dir="cuquantum/densitymat/jax/cppsrc"),
        CMakeExtension("custabilizer_jax_cppsrc",
                       source_dir="cuquantum/stabilizer/jax/cppsrc"),
    ],
    cmdclass=dict(
        build_ext=CMakeBuild,
        bdist_wheel=CustomBdistWheel,
        editable_wheel=CustomBuildEditable,
    ),
    packages=[
        "cuquantum.densitymat.jax",
        "cuquantum.densitymat.jax.pysrc",
        "cuquantum.stabilizer.jax",
        "cuquantum.stabilizer.jax.pysrc",
    ],
    package_data={
        "cuquantum.densitymat.jax": ["**/*.so"],
        "cuquantum.stabilizer.jax": ["**/*.so"],
    },
    exclude_package_data={
        "cuquantum.densitymat.jax": ["cppsrc/*"],
        "cuquantum.stabilizer.jax": ["cppsrc/*"],
        "": ["tests/*"]
    },
    include_package_data=True,
    zip_safe=False
)
